# -*- coding: utf-8 -*-
"""Task_Taiyo_AI (1).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mFfw2_7mEPQdjrm6x7RaAlXphhdeJWzJ

Importing the required Libraries
"""

pip install trafilatura

import numpy as np
import spacy
import requests
import trafilatura
import json
import pandas as pd
import bs4
from bs4 import BeautifulSoup
from requests.models import MissingSchema
import requests

pip install beautifulsoup4

"""Extracting Texts using Beautifulsoup4"""

from urllib.request import urlopen
from bs4 import BeautifulSoup

url = "https://etenders.gov.in/eprocure/app"
html = urlopen(url).read()
soup = BeautifulSoup(html, features="html.parser")

# kill all script and style elements
for script in soup(["script", "style"]):
    script.extract()    # rip it out

# get text
text = soup.get_text()

# break into lines and remove leading and trailing space on each
lines = (line.strip() for line in text.splitlines())
# break multi-headlines into a line each
chunks = (phrase.strip() for line in lines for phrase in line.split("  "))
# drop blank lines
text = '\n'.join(chunk for chunk in chunks if chunk)

print(text)